sudo: required
services:
- docker
language: go
go:
- 1.9
env:
  global:
  - PATH=/home/travis/gopath/bin:$PATH DEBIAN_FRONTEND=noninteractive
  - GPG_NAME=3D86849D
  - GPG_FINGERPRINT=E37EC0B895A9AC27DC4919AB96CEB4B93D86849D
  - secure: W8Fsifsz4FUzZZPKTurNk8S1u77qwB+AqBMuGA3hj0LtiqzTauUouzMoiw8R4OrDONv0uVjRuI9JIZ2+YLAPRXqD+cY284bM2hNwepRMmMyTzY9C1A+3CW6x7SPuwndYM5qtgY3+g6Qi/P/+VC7kVQ1mG5Sxv24AC77Im7aHmeqra3RhaVuiRzK7Royv0L7yAC3t9Impzww8yM19vDHMf66sPa7GmuWZdlRoBY6J3aRN+3tWCtidIKhLfr7GccYPhYQqfzfXVU4H3rcyJumJUguaUHuKwxArjdegC8TaLX6/Z2Ujme1cvV2UgCLYnl0TeKz8ARJA4lf7waFHGK2FEC6067gy+dPelUAbT/ZXm95miyJPFssFPcHIfKMso41OHJPo2hP2ea+yav8IeQzCVm+5nwn6zIL7gair1RO36MQ7bbDX82MRbJBVFb/w3TQLHCCLTsdws+aIbt7jqM4turdxu1RWUgdlIGY4C6xIxOfdLUtHGVungh31dMykXJvKYqPrUKpUyIdV3CpU8ZXZM4YfaNQsV8GtYKFEdbEQdV0EIi5l+DDQ3GyOBHNjzSl0/pYBMG2QoGbhi6GwlkfYfbuwU10ARCFpqW7BsdeMRGyYbi4/HkQLA9xPhVn4+82tHMuNzKJriIRJdzyavhWLHAul+CqTEcviNn7CkQUROcE=
  - secure: M9vYLX55brMq1CwZz2My1CE+E0iuQdnuN5mlInK0P+gVVDZfYTqNCEQXgM0IVISi7eB5Y3Uq1tx4L35Rwzqa0GvVru5uJzThOP6DJT1KwMuB5vqpIPCmrBNGoeuYqWoNWYjhUIGfoyhKY3PPJKPvQm2psVUIQ2XYi0yrTG70skrPcsfubwR6IAEeOD/ujHMu03r1frcM9TfVUNqogOrfCS9jSVR139k/87nWXhp2ALQ4zwYoTmSoorP8OaJ5acFVIHlKmBu+l67zJsnLoYSKrarKFy1c0lgVdQwHcpC49WxVgY1NyfkQsEj2vxZWNpd4fK/6VoV2mtXm4Tftt4MU9xTwkRAIC/DLzpNnTN3sbj5GLPoHv62F5KIIurnM12lErOdS7PjN6jAqMUtpCFal9EBGjB4YSUblYI+9w2xsQrNnWaVnWcgYk1lYW2p0woQ54e4BXbEjKskEKInfgeOGmHU6BkvJhEAHv7aQszsoA2gh0Sq9Er7G1VXLBJVQ6u2AFblr9wEYtcxa6rkSNYoB4VCEDgxTbYzYuK4F8iMGZhuUt2QsDJzRnJNcLHRPXrJwQMT3ZM+pjOv/dpztuP0bpZmsr7Mdaxq/RIAcMQoQ93ABULjm8ZbOJ+s740jcfGr3FTBs1PPjdaApFihHSXM5FV8TuBx6Ca3kFL007zayglk=
before_install:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then  openssl aes-256-cbc -K $encrypted_b913830a84ee_key
  -iv $encrypted_b913830a84ee_iv -in usacloud_gpg_key.enc -out usacloud_gpg_key -d;
  fi
- go get -u github.com/golang/lint/golint
script:
- make test
- make lint-docs
before_deploy:
- if [ "$TRAVIS_BRANCH" == "master" ]; then make docker-build; docker pull sacloud/rpm-build:latest;
  docker pull sacloud/deb-build:latest; make rpm deb; fi
- go get github.com/aktau/github-release
- mkdir -p ~/bin
- git clone https://github.com/github/hub.git && cd hub && script/build -o ~/bin/hub
  && cd ..
- echo $TRAVIS_BRANCH
- git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
- git fetch
- git checkout master || git checkout -b master origin/master
- git checkout $TRAVIS_BRANCH
- git fetch --depth=1000
deploy:
- provider: script
  script: scripts/release.pl --task=upload-to-github-release && scripts/release.pl
    --task=upload-master-to-github-release && scripts/release_homebrew.sh && scripts/release_docker_image.sh
    && scripts/release_website.sh
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: scripts/release.pl --task=create-pullrequest --current-branch=$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^bump-version-.*$"
notifications:
  slack:
    secure: SDNdXvz3/aq3oDuFlwKzlm2V3Mok44mum2Wbb1vnuj9cF5kyDknE/WnkNqTo/k8oKZpqQUxR+bxP/DRbMeERsvbpLF5HQ3mYfvXBB3ED3fWEh0YBweRNfc6kHE4Dx03nNYKqOcxLP/lT9x+ix3kkjASrpknm/hAs7tkH0PYgbCDkWCHEh2IgkKDjKuSxzotcwW54i3FFZR8+zqtuS5DWX6WaxIns3DM3+7D4W+bT4San1FN18nzzclIs4NR6/lAw4lQPF2+2IN2sQTKpnvue2qc/3lADxUK/Fdg5Q0ov39KqO2a92tV6xFrL7kNuAx9pAjRpeIwjxo/K8x0kUukQ1OXrrA6y+MT86fcEZ8eydIXJnRjdMfyLXtTNelqqt2E2qJT8a3NMuHDB4DI7wvn/rhJYBr87XQWbsT2YtuaI50quitaExnm0wdjKA8ETGkx6R3jNXsQ0OFFVPyM/4NHoLiTVHc9OyjL6coO8/XzaGeOH7cuz9K6NL+W3YZVQJ6WyquC8mKbWe79IHKJe1NoZSFntJ6An5wwXafyz/Lal7UB1Jl5Q+YEMDdxC+/t3ETDtwRJAyyj2RD0UpT7R5I6MfYMxM45lky8DjMZ2CELQlkgOEZp0V7yB79kxiihBmgK6x1YvDzSCgBxKfjJPF/jKls4c2cN8y+LQZyDVJXmTuwY=
